apiVersion: xl/v1
kind: Import
metadata:
  imports:
  - xebialabs/xld-microservice-ecommerce-infra-env.yaml
  - xebialabs/xlr-microservice-ecommerce-pipeline-ci-cd.yaml
  - xebialabs/xlr-microservice-ecommerce-pipeline-destroy.yaml